"""create app_app app_app_config auth_api_key and add app_id to app_conversation

Revision ID: 851e7777c56f
Revises: 0959a193ccda
Create Date: 2026-06-26 17:49:23.911060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851e7777c56f'
down_revision: Union[str, Sequence[str], None] = '0959a193ccda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_app',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), server_default='chatbot', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('published_config_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_app'))
    )
    op.create_index(op.f('idx_app_app_user_id'), 'app_app', ['user_id'], unique=False)
    op.create_table('app_app_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), server_default='1024', nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_app_config'))
    )
    op.create_index(op.f('idx_app_app_config_app_id'), 'app_app_config', ['app_id'], unique=False)
    op.create_table('auth_api_key',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_api_key'))
    )
    op.create_index(op.f('idx_auth_api_key_app_id'), 'auth_api_key', ['app_id'], unique=False)
    op.create_index(op.f('idx_auth_api_key_key_hash'), 'auth_api_key', ['key_hash'], unique=False)
    op.create_index(op.f('idx_auth_api_key_user_id'), 'auth_api_key', ['user_id'], unique=False)
    op.add_column('app_conversation', sa.Column('app_id', sa.UUID(), nullable=True))
    op.create_index(op.f('idx_app_conversation_app_id'), 'app_conversation', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_app_conversation_app_id'), table_name='app_conversation')
    op.drop_column('app_conversation', 'app_id')
    op.drop_index(op.f('idx_auth_api_key_user_id'), table_name='auth_api_key')
    op.drop_index(op.f('idx_auth_api_key_key_hash'), table_name='auth_api_key')
    op.drop_index(op.f('idx_auth_api_key_app_id'), table_name='auth_api_key')
    op.drop_table('auth_api_key')
    op.drop_index(op.f('idx_app_app_config_app_id'), table_name='app_app_config')
    op.drop_table('app_app_config')
    op.drop_index(op.f('idx_app_app_user_id'), table_name='app_app')
    op.drop_table('app_app')
    # ### end Alembic commands ###
